#
# Make sure to check the documentation at http://goreleaser.com
#

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=1
    main: ./cmd/chip8
    ldflags:
      - -X github.com/benc-uk/chip8/pkg/emulator.Version={{ .Version }}
    goos:
      - linux
      - windows
    goarch:
      - amd64
    binary: chip8

# replaces goos values with more readable names
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: '{{ time "2006-01-02" }}-snap'

release:
  draft: false
  prerelease: false
  header: |
    ## 👓 Golang CHIP-8 Release

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^[Mm]erge"
      - "[Rr]eadme"
      - "[Ll]int"
