name: CI Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Run Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: "^1.16.4"

      - name: Run lint and format checks
        run: make lint

  ci-build:
    name: Code Check & CI build
    runs-on: ubuntu-latest

    steps:
      # Checkout code from repo
      - name: Checkout repo
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: "^1.16.4"

      - name: Install dev packages
        run: sudo apt-get install -y xorg-dev libasound2-dev

      # Run tests
      - name: Run tests
        run: make test

      # Check build
      - name: Run build
        run: make build
